default_stages: [commit]
repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args: [--in-place]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        stages: [commit, manual]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
      - id: autopep8
        name: autopep8-minimal
        stages: [manual]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.0
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py37-plus, --keep-percent-format]
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        stages: [commit, manual]
