# Autogenerated by devscripts/update-version.py

__version__ = '2023.05.26.025817'

RELEASE_GIT_HEAD = '4ad58667c102bd82a7c4cca8aa395ec1682e3b4c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
