# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.12.111529'

RELEASE_GIT_HEAD = '1350d4f22b38dbb4ee5c3652a75aa89b2acb0a5e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'pukkandan/yt-dlp-dev'

ORIGIN = 'pukkandan/yt-dlp-dev'

_pkg_version = '2024.04.12.111529'
