# Autogenerated by devscripts/update-version.py

__version__ = '2023.07.15.111347'

RELEASE_GIT_HEAD = '2a96ff6052e2c7dd75db7b44d1c03ac9e0dfaf7e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
