name: Quick Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    name: Core Test
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install test requirements
      run: pip install pytest pycryptodomex
    - name: Run tests
      run: ./devscripts/run_tests.sh core
  lint:
    name: Linter
    if: "!contains(github.event.head_commit.message, 'ci skip all')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Make lazy extractors
      run: python devscripts/make_lazy_extractors.py
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --hook-stage manual --all-files
